import argparse
import csv
from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


def load_train_metrics(metrics_path: str) -> Tuple[List[int], List[float], List[float]]:
    path = Path(metrics_path)
    if not path.exists():
        raise FileNotFoundError("Metrics CSV not found: {}".format(path))

    epochs: List[int] = []
    train_losses: List[float] = []
    val_losses: List[float] = []

    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        required = {"epoch", "train_loss", "val_loss"}
        if not reader.fieldnames or not required.issubset(set(reader.fieldnames)):
            raise ValueError(
                "Metrics CSV must contain columns: epoch, train_loss, val_loss. "
                "Got: {}".format(reader.fieldnames)
            )

        for row in reader:
            if not row:
                continue
            epochs.append(int(float(row["epoch"])))
            train_losses.append(float(row["train_loss"]))
            val_losses.append(float(row["val_loss"]))

    if not epochs:
        raise ValueError("Metrics CSV has no rows: {}".format(path))

    return epochs, train_losses, val_losses


def plot_losses(
    epochs: List[int],
    train_losses: List[float],
    val_losses: List[float],
    output_path: str,
    title: str,
    dpi: int,
) -> None:
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 6))
    plt.plot(epochs, train_losses, label="Train Loss", marker="o", linewidth=1.8, markersize=3)
    plt.plot(epochs, val_losses, label="Val Loss", marker="s", linewidth=1.8, markersize=3)
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(title)
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out, dpi=dpi)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot train/val loss curves from train_metrics.csv."
    )
    parser.add_argument(
        "--metrics-path",
        default="outputs/train_metrics.csv",
        help="Path to metrics CSV generated by run_train.py.",
    )
    parser.add_argument(
        "--output-path",
        default="outputs/train_val_loss_curve.png",
        help="Path to save the loss curve image.",
    )
    parser.add_argument(
        "--title",
        default="Train/Val Loss vs Epoch",
        help="Chart title.",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=180,
        help="Output image DPI.",
    )
    args = parser.parse_args()

    epochs, train_losses, val_losses = load_train_metrics(args.metrics_path)
    plot_losses(
        epochs=epochs,
        train_losses=train_losses,
        val_losses=val_losses,
        output_path=args.output_path,
        title=args.title,
        dpi=args.dpi,
    )
    ax = plt.gca()
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    print("Saved loss curve:", args.output_path)
    print("Read metrics from:", args.metrics_path)
    print("Epochs:", len(epochs))


if __name__ == "__main__":
    main()
